version: '3.8'

services:
  # Django Web Application
  web:
    build: .
    command: gunicorn tech_routing.wsgi:application --bind 0.0.0.0:8000 --workers 2 --threads 4 --timeout 120
    volumes:
      - .:/app
      - static_volume:/static
      - media_volume:/media
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=tech_routing.production_settings
      - DEBUG=False
      - SECRET_KEY=django-insecure-change-this-in-production
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY:-AIzaSyCZCEanL50XqkGdej2VdZUCwRrkcf1RrYw}
      - DATABASE_URL=postgresql://django_user:django_password@db:5432/tech_routing
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=tech_routing
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U django_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for Caching
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:

