# Generated by Django 5.2.7 on 2025-10-28 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_assignment_technician"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicerequest",
            name="required_skills",
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="required_skill",
            field=models.ForeignKey(
                blank=True,
                help_text="Required skill for this service (one skill per request)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service_requests",
                to="core.skill",
            ),
        ),
    ]
