# Generated by Django 5.2.7 on 2025-10-28 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="plaintext_password",
            field=models.CharField(
                blank=True,
                help_text="Plaintext password for admin reference",
                max_length=255,
                null=True,
            ),
        ),
    ]
